version = 1

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/stanzinofree/KREDS:dash"
  dependencies_vendored = true

[[transformers]]
name = "prettier"

[[transformers]]
name = "gofumpt"